version: '3.4'

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=db_example
      - MYSQL_ROOT_PASSWORD=some_password
    ports:
      - '3306:3306'
  demo:
    depends_on:
      - db
    image: demo
    links:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile.demo
    environment:
      - MYSQL_HOST=db
    ports:
      - 8080:8080
